## Functions 

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6,7],np.int8)

In [3]:
type(a)

numpy.ndarray

In [4]:
a.dtype

dtype('int8')

In [5]:
a.shape

(7,)

In [6]:
a.ndim

1

In [7]:
a.nbytes

7

In [8]:
a.argmax()

6

In [9]:
a.argmin()

0

In [10]:
a.argsort()

array([0, 1, 2, 3, 4, 5, 6], dtype=int64)

In [11]:
u = np.zeros(7)

In [12]:
print(u)

[0. 0. 0. 0. 0. 0. 0.]


In [13]:
u = np.zeros((7,7))

In [14]:
print(u)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [15]:
v = np.ones((7,7))

In [16]:
v

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [17]:
o = np.arange(99)

In [18]:
o = o.reshape((3,33))

In [19]:
o.shape

(3, 33)

In [20]:
o.sum()

4851

In [21]:
o.sum(axis = 0 )

array([ 99, 102, 105, 108, 111, 114, 117, 120, 123, 126, 129, 132, 135,
       138, 141, 144, 147, 150, 153, 156, 159, 162, 165, 168, 171, 174,
       177, 180, 183, 186, 189, 192, 195])

In [22]:
o.sum(axis = 1)

array([ 528, 1617, 2706])

In [23]:
a = np.array([1,2,3,4,5,6,7]) + 2

In [24]:
a

array([3, 4, 5, 6, 7, 8, 9])

In [25]:
a = a - 2

In [26]:
a == u

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False]])

In [27]:
a.T

array([1, 2, 3, 4, 5, 6, 7])